
import java.awt.Toolkit;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.filechooser.*;//ใส่ไว้อาจจะใช้//มีไว้ใช้เรียกหน้าตางเลือกไฟล์
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author 5620610007
 */
public class Frame1 extends javax.swing.JFrame {
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        headText = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        level = new javax.swing.JLabel();
        subject = new javax.swing.JLabel();
        txtSubject = new javax.swing.JTextField();
        score = new javax.swing.JLabel();
        txtScore = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        save = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        showData = new javax.swing.JButton();
        deleteData = new javax.swing.JButton();
        warning = new javax.swing.JLabel();
        copyright = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("5620610007 อภิวัฒน์ ดินแดง 5620610040 มาเรีย แวดาโอะ ");
        setBackground(new java.awt.Color(204, 255, 204));
        setForeground(new java.awt.Color(153, 255, 153));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("LOGO ICT.png")));
        getContentPane().setLayout(null);

        headText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        headText.setForeground(new java.awt.Color(0, 153, 153));
        headText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headText.setText("MiniProjectOOP");
        headText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(headText);
        headText.setBounds(200, 20, 180, 30);

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.setText("ชื่อ-สกุล");
        getContentPane().add(name);
        name.setBounds(40, 80, 80, 30);

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(120, 80, 360, 30);

        level.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        level.setText("ระดับการเรียน");
        getContentPane().add(level);
        level.setBounds(40, 130, 90, 30);

        subject.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subject.setText("วิชาเรียน");
        getContentPane().add(subject);
        subject.setBounds(40, 170, 70, 30);

        txtSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubjectActionPerformed(evt);
            }
        });
        getContentPane().add(txtSubject);
        txtSubject.setBounds(120, 170, 360, 30);

        score.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        score.setText("คะแนน");
        getContentPane().add(score);
        score.setBounds(40, 234, 70, 20);

        txtScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScoreActionPerformed(evt);
            }
        });
        getContentPane().add(txtScore);
        txtScore.setBounds(120, 230, 360, 30);

        jRadioButton1.setSelected(false);
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setText("มัธยมศึกษา");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(130, 130, 100, 25);

        jRadioButton1.setSelected(false);
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setText("ปริญญาตรี");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(240, 130, 90, 25);

        jRadioButton1.setSelected(false);
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton3.setText("ปริญญาโท/เอก");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(330, 130, 150, 25);

        save.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(150, 330, 130, 30);

        reset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset);
        reset.setBounds(280, 330, 130, 30);

        showData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        showData.setText("Show Data");
        showData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDataActionPerformed(evt);
            }
        });
        getContentPane().add(showData);
        showData.setBounds(220, 290, 130, 30);

        deleteData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deleteData.setText("Delete All Data");
        deleteData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDataActionPerformed(evt);
            }
        });
        getContentPane().add(deleteData);
        deleteData.setBounds(220, 380, 130, 30);

        warning.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        warning.setText("*กรุณาป้อนคะแนนตั้งแต่ 1-100 เท่านั้น");
        getContentPane().add(warning);
        warning.setBounds(190, 270, 240, 15);

        copyright.setFont(new java.awt.Font("Tahoma", 0, 5)); // NOI18N
        copyright.setText("Copyright@007,040");
        getContentPane().add(copyright);
        copyright.setBounds(490, 440, 50, 10);

        setSize(new java.awt.Dimension(592, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubjectActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScoreActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
     File file = new File("D:/5620610007/Score.txt");	
					
            if (!file.exists()) {
		try {
		    file.createNewFile();
		   } catch (IOException e) {
		     e.printStackTrace();
		   }
		} 				  
		try {
		BufferedWriter wr = new BufferedWriter(new FileWriter(file, true)); 
		wr.write(txtName.getText( ));
                //wr.write(",");
		wr.write("\t");
// Check Checkbox--------------------------------------------------------------- 
                
		if( jRadioButton1.isSelected()){
		    wr.write("มัธยมศึกษา");
                   // wr.write(",");
                    wr.write("\t");
		} else if ( jRadioButton2.isSelected()) {
	            wr.write("ปริญญาตรี");
                   // wr.write(",");
                    wr.write("\t");	
		} else if ( jRadioButton3.isSelected()) {
	            wr.write("ปริญญาโท/เอก");
                   // wr.write(",");
                    wr.write("\t");		
	        } else {
		/*JOptionPane.showMessageDialog(null,
			                     "You not Select.");//แจ้งเตือน*/	
		}		
		wr.write(txtSubject.getText( ));//เขียนวิชาลงไฟลื
               // wr.write(",");
		wr.write("\t");                               
	        wr.write(txtScore.getText( ));//เขียนคะแนนลงไฟล์
               // wr.write(",");
                wr.write("\t");
//ถ้าเลือกมัธยม--------------------------------------------------------------------------                
        if( jRadioButton1.isSelected()){ 
           int txtScore;
           String grade;
           txtScore = (Integer.valueOf(this.txtScore.getText())).intValue();
           try{
               txtScore = (Integer.valueOf(this.txtScore.getText())).intValue();
                        if(txtScore >= 80){
                                grade="4";
			}
			else 	if(txtScore >=75){
                                grade="3.5";
			}
			else 	if(txtScore >=70){
                                grade="3";
			}
			else 	if(txtScore >= 65){
                                grade="2.5";
			}
			else 	if(txtScore >= 60){
                                grade="2";
			}
			else 	if(txtScore >= 55){	
                                grade="1.5";
			}
			else 	if(txtScore >= 50){
                                grade="1";
			}
			else{
                                grade="0";
			} 
                wr.write(grade);
                //wr.write(",");
          }catch(NumberFormatException ex){
        }                              
//ถ้าเลือกป.ตรี                       
         } else if ( jRadioButton2.isSelected()) {
           int txtScore;
               String grade;    
               txtScore = (Integer.valueOf(this.txtScore.getText())).intValue();
               try{
                 txtScore = (Integer.valueOf(this.txtScore.getText())).intValue();
                 
                 	if(txtScore >= 80){
                            grade="A";
			}
			else 	if(txtScore >=75){
                                grade="B+";
			}
			else 	if(txtScore >=70){
                                grade="B";
			}
			else 	if(txtScore >= 65){
                                grade="C+";
			}
			else 	if(txtScore >= 60){
                                grade="C";
			}
			else 	if(txtScore >= 55){	
                                grade="D+";
			}
			else 	if(txtScore >= 50){
                                grade="D";
			}
			else{
                                grade="E";
			} 
                wr.write(grade);
               // wr.write(",");
            }catch(NumberFormatException ex){                
            }
//ถ้าเลือก ป.โท/เอก				   	
	 } else if ( jRadioButton3.isSelected()) {
	   int txtScore;
               String grade;    
               txtScore = (Integer.valueOf(this.txtScore.getText())).intValue();
               try{
                 txtScore = (Integer.valueOf(this.txtScore.getText())).intValue();                 
                        if(txtScore >= 85){
                            grade="Excellent";
			}
			else 	if(txtScore>=60){
                            grade="Pass";
			}
			else{
                            grade="Fail";
			}
                wr.write(grade);
                //wr.write(",");    
            }catch(NumberFormatException ex){                
            }			   		
	 }
	    wr.newLine();//อ่านบรรทัดใหม่				              
	    wr.close();//ปิดไฟล์เลย 
	} catch (IOException e) {
	e.printStackTrace();
	}
                JOptionPane.showMessageDialog(null,
			                     "บันทึกข้อมูลเรียบร้อยแล้ว.");
    }//GEN-LAST:event_saveActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
       txtName.setText("");
       jRadioButton1.setSelected(false);
       jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       txtSubject.setText("");
       txtScore.setText("");	
    }//GEN-LAST:event_resetActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
      
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void showDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDataActionPerformed
 //รอทำต่อตอนนี้เหลือแสดงข้อมูลเป็นตาราง-------------------------------------------------------------------        
    JFrame myFrame = new JFrame ( );
    myFrame.setTitle("5620610007 อภิวัฒน์ ดินแดง 5620610040 มาเรีย แวดาโอะ");//ข้อความ Title
    myFrame.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("LOGO ICT.png")));//ใส่ LOGO
   
	myFrame.getContentPane().setLayout ( null );
        String listName[] = {"Name-Surname","Level","Subject","Score","Grade"};//เพิ่มคอลัมแบบ1
        DefaultTableModel tableModel = new DefaultTableModel (listName,0);
        try {
	    FileInputStream fstream = new FileInputStream("D:/5620610007/Score.txt");
            DataInputStream instream = new DataInputStream(fstream);
            BufferedReader bf = new BufferedReader(new InputStreamReader(instream));
            String line;
            //เพิ่มคอลัมอีกแแบบ2 
             /* tableModel.addColumn ( "Name-Surnameอภิวัฒน์ดินแดง" );
		tableModel.addColumn ( "Level5620610007" );
		tableModel.addColumn ( "Subject" );
		tableModel.addColumn ( "Score" );
		tableModel.addColumn ( "Grade" );*/
// อ่านไฟล์ทีละบรรทัด--------------------------------------------------------------------------
    while ((line = bf.readLine()) != null) {
	    String set[] = line.split("\t"); //คัดแยกคำที่อยู่ระหว่าง "," ให้ไปโชว์ในแต่ละ คอลัมของตาราง               
            tableModel.addRow(set);//นำข้อมูลที่ได้ set โชว์ขึ้นใน ตาราง 		
	    JTable table = new JTable ( );	
            table.setModel ( tableModel );
            JScrollPane tableScroll = new JScrollPane ( table );         
            tableScroll.setLocation ( 20, 20 );
	    tableScroll.setSize ( 900, 500 );//กำหนดขนาดตาราง
            myFrame.getContentPane().add ( tableScroll );               
   }
// ปิด input stream -------------------------------------------------------------------------------------------------
             instream.close();
            } catch (Exception e) {
                  System.out.println("Error: " + e.getMessage());
              }
	 myFrame.setSize ( 960, 600 );//กำหนดขนาดของเฟลม
         setSize(new java.awt.Dimension(568, 426));
         myFrame.setLocationRelativeTo(null);//กำหนดให้เฟลมแสดงกลางหน้าจอเวลารัน
         //myFrame.setDefaultCloseOperation ( WindowConstants.EXIT_ON_CLOSE );//เมทอดกดปิดหน้าต่างตารางแล้วปิดทั้งโปรแกรม
         myFrame.setVisible ( true );
         
//อ่านไฟล์แบบ Text Mode------------------------------------------------------------------------------------------------       
/*    System.out.println("Name-Surname\tLevel\tSubject\tScore\tGrade");
      try {
// อ่านไฟล์ชื่อ textfile.txt
    FileInputStream fstream = new FileInputStream("D:/5620610007/Score.txt");
    DataInputStream instream = new DataInputStream(fstream);
    BufferedReader bf = new BufferedReader(new InputStreamReader(instream));
    String line;
    
// อ่านไฟล์ทีละบรรทัด
    while ((line = bf.readLine()) != null) {
        System.out.println(line);
    }
// ปิด input stream
    instream.close();
} catch (Exception e) {
    System.out.println("Error: " + e.getMessage());
}*/   
    }//GEN-LAST:event_showDataActionPerformed

    private void deleteDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDataActionPerformed
        
      FileOutputStream file_outputstream = null;
        try {
            file_outputstream = new FileOutputStream ("D:/5620610007/Score.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Frame1.class.getName()).log(Level.SEVERE, null, ex);
        }
      BufferedOutputStream buffered_outputstream = new BufferedOutputStream ( file_outputstream );
        try {
            buffered_outputstream.flush ();
        } catch (IOException ex) {
            Logger.getLogger(Frame1.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null,
			                     "ลบข้อมูลทั้งหมดเรียบร้อยแล้ว.");
    }//GEN-LAST:event_deleteDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel copyright;
    private javax.swing.JButton deleteData;
    private javax.swing.JLabel headText;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JLabel level;
    private javax.swing.JLabel name;
    private javax.swing.JButton reset;
    private javax.swing.JButton save;
    private javax.swing.JLabel score;
    private javax.swing.JButton showData;
    private javax.swing.JLabel subject;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtScore;
    private javax.swing.JTextField txtSubject;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables

}
